version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8080:8080"
    command: sh -c "sleep 10 && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=8080"
    depends_on:
      - mysql
      - redis
    networks:
      - auction-network

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: auction_catalog
      MYSQL_USER: auction
      MYSQL_PASSWORD: auction
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - auction-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - auction-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - auction-network

networks:
  auction-network:
    driver: bridge

volumes:
  mysql-data:

